dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run build
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
    - stage: deploy
      script:
        - npm run build
        - npm install -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN"