dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run build
        - npm run lint
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
    - stage: deploy
      script:
        - npm run build -- --prod
        - npm install -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN"
